name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  
  # 모든 파일을 읽을 수 있게

jobs:
  build:
    runs-on: ubuntu-latest  # ubuntu에서 실행
    steps:
      - uses: actions/checkout@v3
      - name: install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -Dtestskip
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Repository secrets에 설정해놓은 값

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/server .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
        # 여기까지가 인텔리제이에서 빌드하는 과정
        
  deploy:
    needs: build  # 위의 build가 정상적으로 실행되어야지만 실행됨
    runs-on: ubuntu-latest
    steps:
      - name: Set target IP
      - run: |
          CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.NGINX_IP }}/env")  # 현재 돌아가고 있는 게 BLUE인지 GREEN인지 체크를 해야 함
          echo $CURRENT_UPSTREAM
          if [ $CURRENT_UPSTREAM -ne blue -o $CURRENT_UPSTREAM -ne green ]; then  # not equal
            #CURRENT_UPSTREAM=blue  # 변수 대입
          fi  # if 닫는 거
          if [ $CURRENT_UPSTREAM -eq blue ]; then  # blue 일 때
            echo "CURRENT_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV  #blue_ip를 current_ip로 들고와라 echo로 변수에 저장 - run이 끝나고도 사용 가능
            echo "STOPPED_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          fi
          elif [ $CURRENT_UPSTREAM -eq green ]; then  # green 일 때
            echo "CURRENT_IP=${{ secrets.GREEN_IP }}" >> $GITHUB_ENV
            echo "STOPPED_IP=${{ secrets.BLUE_IP }}" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          fi
          else
            echo "error"
            exit 1
          fi
      - name: Docker compose
        uses: appleboy/ssh-action@master  # ssh에 접속할 수 있도록 하는 것
        with:
          username: ubuntu
          host: ${{ env.STOPPED_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
            docker-compose up -d
      - name: Check deploy server URL PORT 8080
        uses: jtalk/url-health-check-action@v3
        with: 
          url: http://${{ env.STOPPED_IP }}:8080/env
          max-attempts: 3   # 3번 요청
          retry-delay: 10s  # 10초마다
      - name: Check deploy server URL PORT 8081
        uses: jtalk/url-health-check-action@v3
        with: 
          url: http://${{ env.STOPPED_IP }}:8081/env
          max-attempts: 3
          retry-delay: 10s

      - name: Change nginx upstream
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.NGINX_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            docker exec -i nginxserver bash -c 'echo "set \$server_env ${{ env.TARGET_UPSTREAM }}"; >> /etc/nginx/conf.d/server-env.inc && service nginx reload'  # nginxserver 만들어뒀던 container 이름

      - name: Stop current server
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.CURRENT_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            docker stop prod1
            docker stop prod2
            docker rm prod1
            docker rm prod2

        
